class PhoneValidator {
  final List<Map> _countyPhones = [
    {'country': 'China', 'phLength': 13, 'countryCode': '+86'},
    {'country': 'Mozambique', 'phLength': 12, 'countryCode': '+258'},
    {'country': 'Brazil', 'phLength': 11, 'countryCode': '+55'},
    {'country': 'India', 'phLength': 10, 'countryCode': '+91'},
    {'country': 'United States', 'phLength': 10, 'countryCode': '+1'},
    {'country': 'Pakistan', 'phLength': 10, 'countryCode': '+92'},
    {'country': 'Bangladesh', 'phLength': 10, 'countryCode': '+880'},
    {'country': 'Russia', 'phLength': 10, 'countryCode': '+7'},
    {'country': 'Mexico', 'phLength': 10, 'countryCode': '+52'},
    {'country': 'Japan', 'phLength': 10, 'countryCode': '+81'},
    {'country': 'Philippines', 'phLength': 10, 'countryCode': '+63'},
    {'country': 'Egypt', 'phLength': 10, 'countryCode': '+20'},
    {'country': 'Iran', 'phLength': 10, 'countryCode': '+98'},
    {'country': 'Turkey', 'phLength': 10, 'countryCode': '+90'},
    {'country': 'Germany', 'phLength': 10, 'countryCode': '+49'},
    {'country': 'United Kingdom', 'phLength': 10, 'countryCode': '+44'},
    {'country': 'Italy', 'phLength': 10, 'countryCode': '+39'},
    {'country': 'Kenya', 'phLength': 10, 'countryCode': '+254'},
    {'country': 'Colombia', 'phLength': 10, 'countryCode': '+57'},
    {'country': 'South Korea', 'phLength': 10, 'countryCode': '+82'},
    {'country': 'Canada', 'phLength': 10, 'countryCode': '+1'},
    {'country': 'Nepal', 'phLength': 10, 'countryCode': '+977'},
    {'country': 'Romania', 'phLength': 10, 'countryCode': '+40'},
    {'country': 'Kazakhstan', 'phLength': 10, 'countryCode': '+7'},
    {'country': 'Dominican Republic', 'phLength': 10, 'countryCode': '+1849'},
    {'country': 'Greece', 'phLength': 10, 'countryCode': '+30'},
    {'country': 'Austria', 'phLength': 10, 'countryCode': '+61'},
    {'country': 'Libya', 'phLength': 10, 'countryCode': '+218'},
    {'country': 'Puerto Rico', 'phLength': 10, 'countryCode': '+1939'},
    {'country': 'Jamaica', 'phLength': 10, 'countryCode': '+1876'},
    {'country': 'Trinidad and Tobago', 'phLength': 10, 'countryCode': '+1868'},
    {'country': 'Bahamas', 'phLength': 10, 'countryCode': '+1242'},
    {'country': 'Barbados', 'phLength': 10, 'countryCode': '+1246'},
    {'country': 'Saint Lucia', 'phLength': 10, 'countryCode': '+1758'},
    {'country': 'Guam', 'phLength': 10, 'countryCode': '+1671'},
    {'country': 'Grenada', 'phLength': 10, 'countryCode': '+1473'},
    {
      'country': 'Saint Vincent and the Grenadines',
      'phLength': 10,
      'countryCode': '+1784',
    },
    {
      'country': 'United States Virgin Islands',
      'phLength': 10,
      'countryCode': '+1340',
    },
    {'country': 'Antigua and Barbuda', 'phLength': 10, 'countryCode': '+1268'},
    {'country': 'Isle of Man', 'phLength': 10, 'countryCode': '+44'},
    {'country': 'Dominica', 'phLength': 10, 'countryCode': '+1767'},
    {'country': 'Cayman Islands', 'phLength': 10, 'countryCode': '+345'},
    {'country': 'Bermuda', 'phLength': 10, 'countryCode': '+1441'},
    {'country': 'Guernsey', 'phLength': 10, 'countryCode': '+44'},
    {
      'country': 'Northern Mariana Islands',
      'phLength': 10,
      'countryCode': '+1670',
    },
    {
      'country': 'Saint Kitts and Nevis',
      'phLength': 10,
      'countryCode': '+1869',
    },
    {
      'country': 'Turks and Caicos Islands',
      'phLength': 10,
      'countryCode': '+1649',
    },
    {'country': 'Sint Maarten', 'phLength': 10, 'countryCode': '+'},
    {'country': 'American Samoa', 'phLength': 10, 'countryCode': '+1684'},
    {
      'country': 'British Virgin Islands',
      'phLength': 10,
      'countryCode': '+1284',
    },
    {'country': 'Anguilla', 'phLength': 10, 'countryCode': '+1264'},
    {'country': 'Montserrat', 'phLength': 10, 'countryCode': '+1664'},
    {'country': 'Vatican City', 'phLength': 10, 'countryCode': '+379'},
    {'country': 'Indonesia', 'phLength': 9, 'countryCode': '+62'},
    {'country': 'Vietnam', 'phLength': 9, 'countryCode': '+84'},
    {'country': 'Thailand', 'phLength': 9, 'countryCode': '+66'},
    {'country': 'South Africa', 'phLength': 9, 'countryCode': '+27'},
    {'country': 'Spain', 'phLength': 9, 'countryCode': '+34'},
    {'country': 'Algeria', 'phLength': 9, 'countryCode': '+213'},
    {'country': 'Afghanistan', 'phLength': 9, 'countryCode': '+93'},
    {'country': 'Poland', 'phLength': 9, 'countryCode': '+48'},
    {'country': 'Saudi Arabia', 'phLength': 9, 'countryCode': '+966'},
    {'country': 'Ukraine', 'phLength': 9, 'countryCode': '+380'},
    {'country': 'Yemen', 'phLength': 9, 'countryCode': '+967'},
    {'country': 'Peru', 'phLength': 9, 'countryCode': '+51'},
    {'country': 'Ghana', 'phLength': 9, 'countryCode': '+233'},
    {'country': 'Cameroon', 'phLength': 9, 'countryCode': '+237'},
    {'country': 'Australia', 'phLength': 9, 'countryCode': '+61'},
    {'country': 'Taiwan', 'phLength': 9, 'countryCode': '+886'},
    {'country': 'Syria', 'phLength': 9, 'countryCode': '+963'},
    {'country': 'Zambia', 'phLength': 9, 'countryCode': '+260'},
    {'country': 'Chile', 'phLength': 9, 'countryCode': '+56'},
    {'country': 'Ecuador', 'phLength': 9, 'countryCode': '+593'},
    {'country': 'Netherlands', 'phLength': 9, 'countryCode': '+31'},
    {'country': 'Cambodia', 'phLength': 9, 'countryCode': '+855'},
    {'country': 'Zimbabwe', 'phLength': 9, 'countryCode': '+263'},
    {'country': 'Benin', 'phLength': 9, 'countryCode': '+229'},
    {'country': 'Belgium', 'phLength': 9, 'countryCode': '+32'},
    {'country': 'Jordan', 'phLength': 9, 'countryCode': '+962'},
    {'country': 'Czech Republic', 'phLength': 9, 'countryCode': '+420'},
    {'country': 'Azerbaijan', 'phLength': 9, 'countryCode': '+994'},
    {'country': 'Portugal', 'phLength': 9, 'countryCode': '+351'},
    {'country': 'Hungary', 'phLength': 9, 'countryCode': '+36'},
    {'country': 'United Arab Emirates', 'phLength': 9, 'countryCode': '+971'},
    {'country': 'Belarus', 'phLength': 9, 'countryCode': '+375'},
    {'country': 'Israel', 'phLength': 9, 'countryCode': '+972'},
    {'country': 'Switzerland', 'phLength': 9, 'countryCode': '+41'},
    {'country': 'Paraguay', 'phLength': 9, 'countryCode': '+595'},
    {'country': 'Slovakia', 'phLength': 9, 'countryCode': '+421'},
    {'country': 'New Zealand', 'phLength': 9, 'countryCode': '+64'},
    {'country': 'Ireland', 'phLength': 9, 'countryCode': '+353'},
    {'country': 'Croatia', 'phLength': 9, 'countryCode': '+385'},
    {'country': 'Georgia', 'phLength': 9, 'countryCode': '+995'},
    {'country': 'Luxembourg', 'phLength': 9, 'countryCode': '+352'},
    {'country': 'Guadeloupe', 'phLength': 9, 'countryCode': '+590'},
    {'country': 'Martinique', 'phLength': 9, 'countryCode': '+596'},
    {'country': 'French Guiana', 'phLength': 9, 'countryCode': '+594'},
    {'country': 'Nigeria', 'phLength': 8, 'countryCode': '+234'},
    {'country': 'Myanmar', 'phLength': 8, 'countryCode': '+95'},
    {'country': 'Niger', 'phLength': 8, 'countryCode': '+227'},
    {'country': 'Mali', 'phLength': 8, 'countryCode': '+223'},
    {'country': 'Burkina Faso', 'phLength': 8, 'countryCode': '+226'},
    {'country': 'Chad', 'phLength': 8, 'countryCode': '+235'},
    {'country': 'Somalia', 'phLength': 8, 'countryCode': '+252'},
    {'country': 'Guatemala', 'phLength': 8, 'countryCode': '+502'},
    {'country': 'Tunisia', 'phLength': 8, 'countryCode': '+216'},
    {'country': 'Honduras', 'phLength': 8, 'countryCode': '+504'},
    {'country': 'Togo', 'phLength': 8, 'countryCode': '+228'},
    {'country': 'Hong Kong', 'phLength': 8, 'countryCode': '+852'},
    {'country': 'Serbia', 'phLength': 8, 'countryCode': '+381'},
    {'country': 'Nicaragua', 'phLength': 8, 'countryCode': '+505'},
    {'country': 'El Salvador', 'phLength': 8, 'countryCode': '+503'},
    {'country': 'Singapore', 'phLength': 8, 'countryCode': '+65'},
    {'country': 'Denmark', 'phLength': 8, 'countryCode': '+45'},
    {'country': 'Norway', 'phLength': 8, 'countryCode': '+47'},
    {'country': 'Costa Rica', 'phLength': 8, 'countryCode': '+506'},
    {'country': 'Oman', 'phLength': 8, 'countryCode': '+968'},
    {'country': 'Panama', 'phLength': 8, 'countryCode': '+507'},
    {'country': 'Kuwait', 'phLength': 8, 'countryCode': '+965'},
    {'country': 'Moldova', 'phLength': 8, 'countryCode': '+373'},
    {'country': 'Bosnia and Herzegovina', 'phLength': 8, 'countryCode': '+387'},
    {'country': 'Armenia', 'phLength': 8, 'countryCode': '+374'},
    {'country': 'Lithuania', 'phLength': 8, 'countryCode': '+370'},
    {'country': 'Qatar', 'phLength': 8, 'countryCode': '+974'},
    {'country': 'North Macedonia', 'phLength': 8, 'countryCode': '+389'},
    {'country': 'Latvia', 'phLength': 8, 'countryCode': '+371'},
    {'country': 'Bahrain', 'phLength': 8, 'countryCode': '+973'},
    {'country': 'Estonia', 'phLength': 8, 'countryCode': '+372'},
    {'country': 'Mauritius', 'phLength': 8, 'countryCode': '+230'},
    {'country': 'Cyprus', 'phLength': 8, 'countryCode': '+357'},
    {'country': 'Montenegro', 'phLength': 8, 'countryCode': '+382'},
    {'country': 'Malta', 'phLength': 8, 'countryCode': '+356'},
    {'country': 'Kiribati', 'phLength': 8, 'countryCode': '+686'},
    {'country': 'Malaysia', 'phLength': 7, 'countryCode': '+60'},
    {'country': 'Venezuela', 'phLength': 7, 'countryCode': '+58'},
    {'country': 'Sri Lanka', 'phLength': 7, 'countryCode': '+94'},
    {'country': 'Sweden', 'phLength': 7, 'countryCode': '+46'},
    {'country': 'Liberia', 'phLength': 7, 'countryCode': '+231'},
    {'country': 'Lebanon', 'phLength': 7, 'countryCode': '+961'},
    {'country': 'Gabon', 'phLength': 7, 'countryCode': '+241'},
    {'country': 'Solomon Islands', 'phLength': 7, 'countryCode': '+677'},
    {'country': 'Maldives', 'phLength': 7, 'countryCode': '+960'},
    {'country': 'Belize', 'phLength': 7, 'countryCode': '+501'},
    {'country': 'Micronesia', 'phLength': 7, 'countryCode': '+691'},
    {'country': 'Aruba', 'phLength': 7, 'countryCode': '+297'},
    {'country': 'Marshall Islands', 'phLength': 7, 'countryCode': '+692'},
    {'country': 'Palau', 'phLength': 7, 'countryCode': '+680'},
    {'country': 'Tanzania', 'phLength': 6, 'countryCode': '+255'},
    {'country': 'French Polynesia', 'phLength': 6, 'countryCode': '+689'},
    {'country': 'New Caledonia', 'phLength': 6, 'countryCode': '+687'},
    {'country': 'Greenland', 'phLength': 6, 'countryCode': '+299'},
    {'country': 'Samoa', 'phLength': 5, 'countryCode': '+685'},
    {'country': 'Faroe Islands', 'phLength': 5, 'countryCode': '+298'},
    {'country': 'Cook Islands', 'phLength': 5, 'countryCode': '+682'},
    {'country': 'Niue', 'phLength': 4, 'countryCode': '+683'}
  ];
  List<PhoneModel> getPhoneList() {
    final phones = <PhoneModel>[];
    for (final element in _countyPhones) {
      phones.add(
        PhoneModel(
          element['country'].toString(),
          int.parse(element['phLength'].toString()),
          element['countryCode'].toString(),
        ),
      );
    }
    return phones;
  }

  bool isValidPhone(String countyCode, String phoneNumber) {
    try {
      final phoneModel = getPhoneList()
          .firstWhere((element) => element.countryCode == countyCode);
      return phoneModel.length == phoneNumber.length;
    } catch (e) {
      return false;
    }
  }
}

class PhoneModel {
  String country;
  int length;
  String countryCode;

  PhoneModel(this.country, this.length, this.countryCode);
}
